"""
This script is used to generate Figures B.2(right) and B.3(right), providing illustrations
of the average fraction of cooperation and average collective success of the long-time
population for various strengths of group-level selection in the case of a multilevel
PD scenario and the Tullock contest function group-level update rule. This figure uses 
data included  in the Simulation_Outputs folder, which is generated by running the script 
"loopfvpairwise.py" in the Scripts folder.
"""



import numpy as np
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('TkAgg')
import os


from matplotlib import rc
rc('font',**{'family':'sans-serif','sans-serif':['Helvetica']})
## for Palatino and other serif fonts use:
#rc('font',**{'family':'serif','serif':['Palatino']})
rc('text', usetex=True)

eta = 1.0

plt.figure(1)

"""
Defining files of simulation outputs that will be used to generate figures for pairwise
local group-level victory probability.
"""


script_folder = os.getcwd()
pairwise_folder = os.path.dirname(script_folder)

file1 = pairwise_folder + "/Simulation_Outputs/Rho1xPDgamma1p5_Tullock.txt"
file2 = pairwise_folder + "/Simulation_Outputs/AvgGPDgamma1p5_Tullock.txt"
file3 = pairwise_folder + "/Simulation_Outputs/PeakPDgamma1p5_Tullock.txt"
file4 = pairwise_folder + "/Simulation_Outputs/MeanCoopPDEgamma1p5_Tullock.txt"




def process(list):
	list = list.split(',')
	list = [float(a) for a in list]
	return list

def find_lamb_list(f):
	f.readline()
	lamb_list = f.readline()
	lamb_list = process(lamb_list)
	return lamb_list
	
#victory_prob = "Fermi"
#victory_prob = "pairwise locally normalized"
victory_prob = "Tullock"

def data_list(f):
	f.readline()
		
	quantity_list = f.readline()
	quantity_list = process(quantity_list)
	return quantity_list	
	
def G(alpha,gamma,P,x):
	return P + gamma * x + alpha * (x ** 2.)
	
def rho(x,y,alpha,gamma,P,s,inv_a):
	Gx = G(alpha,gamma,P,x)
	Gy = G(alpha,gamma,P,y)
	if victory_prob == "Fermi":
		return 0.5 + 0.5 * np.tanh(s * (Gx - Gy))
	elif victory_prob == "pairwise locally normalized":
		if Gx == Gy == 0.:
			return 0.5
		else:
			num = Gx - Gy
			denom = np.abs(Gx) + np.abs(Gy)
			return 0.5 + 0.5 * (num / denom)
	elif victory_prob == "Tullock":
		if gamma >= 0:
			G_min = P
		if Gx == G_min and Gy == G_min:
			return 0.5
		else:
			num = (Gx - (G_min))**(inv_a)
			denom = (Gx - (G_min))**(inv_a) + (Gy - (G_min))**(inv_a)
			return num / denom
		
		
def pi_diff(alpha,beta):
	return -(beta + alpha)
		
def lambda_star_PD(alpha,beta,gamma,P,s,inv_a, theta):
	num = pi_diff(alpha,beta) * theta
	denom = rho(1,0,alpha,gamma,P,s,inv_a) - rho(0,1,alpha,gamma,P,s,inv_a)
	return num / denom
	

alpha = -1.
beta = -1.
gamma = 1.5
s = 1.
theta = 1.
P = 1.
inv_a = 2.
	
	
"""
Reading in data from simulation outputs for the case of a multilevel PD scenario with the
Tullock contest group-level victory probability and game-theoretic parameters given by
\gamma = 1.5, \alpha = -1, and \beta = -1.
"""
	
	
f1 = open(file1, 'r+')

lamb_list = find_lamb_list(f1)
print(lamb_list)
print(len(lamb_list))

numerical_rho1x_list = data_list(f1)
numerical_rhox1_list = [1.0 - a for a in numerical_rho1x_list]

print(numerical_rho1x_list)

analytical_rho1x_list = data_list(f1)
analytical_rhox1_list = [1.0 - a for a in analytical_rho1x_list]
print(analytical_rho1x_list)


f1.close()


f2 = open(file2,'r+')

lamb_list = find_lamb_list(f2)
avg_G_list = data_list(f2)

print(avg_G_list)

f2.close()


f4 = open(file4,'r+')

lamb_list = find_lamb_list(f4)
avg_coop_list = data_list(f4)

print(avg_coop_list)

f4.close()



"""
Figure comparing average group-level victory probability of the long-time population when
engaged in pairwise competition with the all-cooperator group.
"""
	

plt.figure(1)

plt.plot(lamb_list,numerical_rhox1_list, lw = 7., label =r"Numerically Computed $\langle \rho(1,\cdot) \rangle_f$")
plt.plot(lamb_list,analytical_rhox1_list, lw = 5., ls = '--', label = r"Analytical Prediction for $\langle \rho(1,\cdot) \rangle_f$")

threshold_lamb = lambda_star_PD(alpha,beta,gamma,P,s,inv_a,theta)
plt.axhline(y = 0.5, lw = 5., ls = '-.', alpha = 0.8, color = 'k')
plt.axvline(x = threshold_lamb, lw = 5., ls = '-.', alpha = 0.8, color = 'k')

plt.axis([0.,40.,0.,1.])

plt.title(r"Collective Success Against All-Cooperator Group", fontsize = 18.)
plt.xlabel(r"Strength of Between-Group Competition $\lambda$", fontsize = 20., labelpad = 10.)
plt.ylabel(r"Victory Probability $\langle \rho(\cdot,1)\rangle_f$", fontsize =18.)

plt.legend(loc = "lower right", fontsize = 16.)

plt.annotate(r"$\lambda^*_{PD}$", xy = (threshold_lamb + 1.5,0.8), fontsize = 20.)

plt.tight_layout()

plt.savefig(pairwise_folder + "/Figures/PD_rho1x_plot_Tullock.png")




"""
Figure providing the average fraction of cooperation achieved under the numerical simulations
after 9,600 timesteps, plotted as a function of the relative strength \lambda of
group-level competition. 
"""

plt.figure(2)

plt.plot(lamb_list,avg_coop_list, lw = 7., label =r"$\langle x \rangle_{f(x)}$")

plt.xlabel(r"Strength of Between-Group Competition $\lambda$", fontsize = 20., labelpad = 10.)
plt.ylabel(r"Fraction of Cooperators $x$", fontsize = 20.)
plt.title(r"Average Cooperation at Steady State $\langle x \rangle_{f(x)}$", fontsize = 18.)

plt.axis([0.,40.,0.,1.])

plt.axhline(y = 0.75, lw = 5., ls = '-.', color = 'k', alpha = 0.8)
plt.axhline(y = 0.5, lw = 5., ls = '-.', color = 'k', alpha = 0.8)

plt.axvline(x = threshold_lamb, lw = 5., ls = '-.', alpha = 0.8, color = 'k')

plt.annotate(r"$x^* = 0.75$", xy = (30.,.775), fontsize =18.)
plt.annotate(r"$\overline{x} = 0.5$", xy = (30.,.525), fontsize =18.)

plt.annotate(r"$\lambda^*_{PD}$", xy = (threshold_lamb + 1.25,0.9), fontsize = 18.)

plt.legend(loc = "lower right", fontsize = 20.)

plt.tight_layout()

plt.savefig(pairwise_folder + "/Figures/avgx_plot_Tullock.png")




"""
Figure providing the average payoff achieved under the numerical simulations
after 9,600 timesteps, plotted as a function of the relative strength \lambda of
group-level competition. 
"""

plt.figure(3)

plt.plot(lamb_list,avg_G_list, lw = 7., label =r"$\langle G(x)\rangle_{f(x)}$")


plt.xlabel(r"Strength of Between-Group Competition $\lambda$", fontsize = 20., labelpad = 10.)
plt.ylabel(r"Average Payoff $G(x)$", fontsize = 20.)

plt.legend(loc = "lower right", fontsize = 16.)

plt.axvline(x = threshold_lamb, lw = 5., ls = '-.', alpha = 0.8, color = 'k')
plt.annotate(r"$\lambda^*_{PD}$", xy = (threshold_lamb + 2.,0.65), fontsize = 20.)


plt.axhline(y = 1.5, lw = 5., ls = '-.', color = 'k', alpha = 0.8)
plt.axhline(y = 1.75, lw = 5., ls = '-.', color = 'k', alpha = 0.8)

plt.annotate(r"$G(x^*)$", xy = (30.,1.795), fontsize =18.)
plt.annotate(r"$G(\overline{x})$", xy = (30.,1.545), fontsize =18.)

plt.axis([0.,40.,0.,2.5])

plt.tight_layout()

plt.savefig(pairwise_folder + "/Figures/avgG_plot_Tullock.png")

plt.show()
